runtime: php55

handlers:
  - url: /styles
    static_dir: styles

  - url: gs://my-project-nurrapi-385700.appspot.com/fotodiri (2).jpeg
    static_files: images/\1
    upload: gs://my-project-nurrapi-385700.appspot.com/fotodiri (2).jpeg

  - url: gs://my-project-nurrapi-385700.appspot.com/fotodiri (2).jpeg
    script: index.php
